//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public Warehouse()
        {
            this.StockTransferDetails = new HashSet<StockTransferDetail>();
            this.StockTransfers = new HashSet<StockTransfer>();
            this.TransferOrderDetails = new HashSet<TransferOrderDetail>();
            this.GoodsReceiptDetails = new HashSet<GoodsReceiptDetail>();
            this.TransferOrders = new HashSet<TransferOrder>();
            this.WarehouseInvoices = new HashSet<WarehouseInvoice>();
            this.WarehouseInvoices1 = new HashSet<WarehouseInvoice>();
        }
    
        public int WarehouseID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int WarehouseCategoryID { get; set; }
        public int LocationID { get; set; }
        public bool IsBook { get; set; }
        public bool IsInvoice { get; set; }
        public bool IsDefault { get; set; }
        public string Remarks { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<StockTransferDetail> StockTransferDetails { get; set; }
        public virtual ICollection<StockTransfer> StockTransfers { get; set; }
        public virtual ICollection<TransferOrderDetail> TransferOrderDetails { get; set; }
        public virtual ICollection<GoodsReceiptDetail> GoodsReceiptDetails { get; set; }
        public virtual ICollection<TransferOrder> TransferOrders { get; set; }
        public virtual ICollection<WarehouseInvoice> WarehouseInvoices { get; set; }
        public virtual ICollection<WarehouseInvoice> WarehouseInvoices1 { get; set; }
    }
}
