//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModel.Models
{
    using System;
    
    public partial class WarehouseInvoiceIndex
    {
        public int WarehouseInvoiceID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Reference { get; set; }
        public string VATInvoiceNo { get; set; }
        public string LocationCode { get; set; }
        public string WarehouseName { get; set; }
        public string Description { get; set; }
        public decimal TotalGrossAmount { get; set; }
        public string SourceWarehouseName { get; set; }
        public string TransferOrderNo { get; set; }
        public string TransferOrderCode { get; set; }
    }
}
